### ISSUE TITLE
Include the list of top-level contracts to analyze per file

### ISSUE THREAD

**Issue by gustavo-grieco** [kupl/VeriSmart-benchmarks#1]
Most of the .sol files define several contracts, but only one of them should be analyzed by tools (the top-level one). For instance:

| Filename          | Contract Name
| ---------------------|--------------------
| 2018-10299.sol | BecToken
| 2018-10376.sol | SMT
| 2018-10468.sol | UselessEthereumToken
| 2018-10706.sol | TokenI
| 2018-11239.sol | Hexagon

It will be very useful if you can provide a list of the contracts to analyze per file, so it is easier to use run tools in the complete benchmark.

**Comment by sunbeomso** [comment]
Hi, thanks for your suggestion.

I have uploaded the lists in the `metadata` directory.
